### PR TITLE
Switch server project to GraphQL.AspNetCore3

### PR DESCRIPTION
**Pull request by Shane32**

### CODE REVIEW

**Comment by sungam3r** [comment]
I would not do that before review GraphQL.AspNetCore3 as a potential successor of server project.

**Comment by sungam3r** [comment]
@Shane32 Would you like to retarget PR to "resurrected" server project?

**Comment by Shane32** [comment]
Yes but let's finish it first. It's 99% done now.

**Comment by Shane32** [comment]
Replaced by #179

**Pull request closed without merging**
