### PR TITLE
Support GraphQL 3.0.0

### PR DESCRIPTION
**Pull request by sungam3r**
draft for #54:
- new nuget source
- drop support for net45/netstandard1.3 - netstandard2.0 only
- move to latest GraphQL preview
- netcoreapp2.0 -> netcoreapp2.2
- update dependencies
- fix xUnit warnings

### CODE REVIEW

**Comment by jquense** [comment]
looks great! I've added you as a collaborator as well. If you like nuget publishing rights i can invite you to the org

**Comment by sungam3r** [comment]
Thanks!

**Comment by rkotenko** [comment]
Could I have an update on when this is going to be merged into master?  The 3.0.0 release of Graphql has had numerous preview releases and I would like to use it and this package.

**Comment by sungam3r** [comment]
I decided to postpone the merge until I figure out what Relay is. When I made edits, I did it without much knowledge about the essence of technology. May be a little later.

**Comment by Yakimych** [comment]
@sungam3r Wow, very nice cleanup! Looks like you've fixed the "obsolete" warnings too. Thanks for putting the time and effort into this!

I can help this test during the week. Is there any way we can get this up as a "preview" NuGet package or something?

Also wondering whether this will still work with .NET Framework 4.8 (unfortunately we're stuck with it for a while on a large project).

**Comment by sungam3r** [comment]
> Also wondering whether this will still work with .NET Framework 4.8 

Everything should work since GraphQL.Relay.csproj targets netstandard2.0.

**Comment by MargaretKrutikova** [comment]
We are considering using `GraphQL` with `relay` at work and would be very much interested in testing this package. Is it possible to publish a pre-release version so that we could test it out? Thanks a lot! 😃

**Comment by sungam3r** [comment]
> Is it possible to publish a pre-release version so that we could test it out?

I don’t see that CI generating an artifact on the AppVeyor [page](https://ci.appveyor.com/project/graphql-dotnet-ci/relay/builds/28582344/artifacts). Means that I need to investigate how to configure CI. Unfortunately now I do not have time for this. PRs are welcome.

**Comment by Yakimych** [comment]
The warning from the logs says
```warning MSB4078: The project file "src\GraphQL.Relay\GraphQL.Relay.csproj" is not supported by MSBuild and cannot be built.```
I am guessing an older version of MSBuild is being used on AppVeyor, but I can't see any build configuration in the repo.

@sungam3r @jquense I would be happy to look into this further, but I am guessing I don't have permissions to see the settings on AppVeyor?

**Comment by Shane32** [comment]
@sungam3r Do you want to leave this issue open?  I've looked through the code changes.  There's some cleanup (e.g. remove excess usings) that probably isn't done yet, but everything of substance has been completed already.  It would certainly be more work to merge changes than redo the changes.  I suggest leaving a note within issue #86 to also review changes within this PR, then close this PR.

**Pull request closed without merging**
