### PR TITLE
Support GraphQL 3.0.0.2026

### PR DESCRIPTION
**Pull request by pedrofialho**
This includes commits from #55.

This updates the GraphQL package to 3.0.0.2026 and fixes breaking changes, mainly the [migration to `IResolveConnectionContext`](https://graphql-dotnet.github.io/docs/migrations/migration3/#iresolvefieldcontext-and-iresolveconnectioncontext) and the [new serialization dependencies](https://graphql-dotnet.github.io/docs/migrations/migration3/#json-parsing-and-serialization).

### CODE REVIEW

**Comment by sungam3r** [comment]
GraphQL.NET v4 is on the way.

**Comment by pedrofialho** [comment]
@sungam3r oh I just saw the 4.0 milestone there. I guess I'll wait then.

**Comment by sungam3r** [comment]
Keep in mind that I don't have time to support this project right now. All the time is spent on GraphQL.NET and some other projects. Also see #55. I already did this a long time ago. I was then stopped by not knowing the relay specification to just merge my PR into `master`. To my shame, I have not yet read it. For a long time I have been carrying the idea that after the v4 release I will be able to switch my focus to related projects like this. Moreover, there will be a good reason - to update the major dependence from the "core" GraphQL.NET project.

**Comment by Shane32** [comment]
Replaced by #80

**Pull request closed without merging**
